kind: Service
apiVersion: v1
metadata:
  name: vra-merdocente-web-app
  labels:
    app: vra-merdocente-web-app
spec:
  selector:
    app: vra-merdocente-web-app
  ports:
    - port: 8080
      name: http
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: vra-merdocente-web-app
  labels:
    app: vra-merdocente-web-app
spec:
  selector:                
    matchLabels:     
      app: vra-merdocente-web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: vra-merdocente-web-app
        version: v1
    spec:
      containers:
      - name: vra-merdocente-web-app
        image: image-registry.openshift-image-registry.svc:5000/umayor/vra-merdocente-web-app:latest
        ports:
        - containerPort: 8080
      restartPolicy: Always
---